const crypto = require("crypto");
const { AwsClient, AwsV4Signer } = require("aws4fetch");

// Cloudflare R2, spoken to through its S3-compatible API.
//
// Media bytes never pass through this server. A Vercel function body is capped
// at 4.5 MB - one short screen recording - so the browser uploads straight to
// the bucket with a URL signed here. The signature binds the content type, the
// exact byte count and the cache header, so a signed URL cannot put anything in
// the bucket other than the file that was checked.
//
// aws4fetch rather than the AWS SDK: one small file with no dependencies, doing
// SigV4 over the fetch and WebCrypto that Node already ships.

const PUT_URL_SECONDS = 10 * 60;

// Read URLs are signed as of the top of the hour, so every request within that
// hour gets byte-for-byte the same URL and the browser cache can do its job.
// Each is valid for two hours from the hour it was signed in, so a URL handed
// out at 10:59 still has an hour of life left in it.
const READ_WINDOW_SECONDS = 60 * 60;

// Keys are generated by server/media.js, never taken from a request, and this
// is the alphabet that file uses. Checked anyway: a key is spliced into a URL
// that carries a signature.
const SAFE_KEY = /^[a-z0-9][a-z0-9._\-/]*$/;

const REQUIRED = ["R2_ACCOUNT_ID", "R2_ACCESS_KEY_ID", "R2_SECRET_ACCESS_KEY", "R2_BUCKET"];

let cached = null;

function env(name) {
  return String(process.env[name] || "").trim();
}

/** Why storage cannot be used, or null when it can. */
function problem() {
  const missing = REQUIRED.filter((name) => !env(name));
  return missing.length
    ? `R2 is not configured: set ${missing.join(", ")}. See .env.example.`
    : null;
}

function settings() {
  if (cached) return cached;
  const reason = problem();
  // Not defaulted, for the reason integrations/crypto.js gives: storage that
  // quietly points somewhere else is worse than storage that says it is missing.
  if (reason) throw new Error(reason);

  const credentials = {
    accessKeyId: env("R2_ACCESS_KEY_ID"),
    secretAccessKey: env("R2_SECRET_ACCESS_KEY"),
  };
  cached = {
    credentials,
    bucket: env("R2_BUCKET"),
    endpoint: `https://${env("R2_ACCOUNT_ID")}.r2.cloudflarestorage.com`,
    publicBase: env("R2_PUBLIC_BASE_URL").replace(/\/+$/, "") || null,
    client: new AwsClient({ ...credentials, service: "s3", region: "auto", retries: 3 }),
  };
  return cached;
}

function isConfigured() {
  return problem() === null;
}

/** 'public' when the bucket has its own address, 'private' when klndr signs each read. */
function mode() {
  return settings().publicBase ? "public" : "private";
}

function isSafeKey(key) {
  return typeof key === "string" && SAFE_KEY.test(key) && !key.split("/").includes("..");
}

function objectUrl(key) {
  if (!isSafeKey(key)) throw new Error(`Refusing an unsafe object key: ${key}`);
  const { endpoint, bucket } = settings();
  return `${endpoint}/${bucket}/${key}`;
}

function bucketUrl(query) {
  const { endpoint, bucket } = settings();
  return `${endpoint}/${bucket}?${query}`;
}

/**
 * Where a browser loads an object from: the bucket's public address when it
 * has one, otherwise klndr's own /media route, which signs the read.
 */
function publicUrl(key) {
  const { publicBase } = settings();
  return publicBase ? `${publicBase}/${key}` : `/media/${key}`;
}

function amzDate(seconds) {
  return new Date(seconds * 1000).toISOString().replace(/[:-]|\.\d{3}/g, "");
}

async function presign(method, key, { headers = {}, expiresIn, signedAt } = {}) {
  const url = new URL(objectUrl(key));
  url.searchParams.set("X-Amz-Expires", String(expiresIn));
  const signer = new AwsV4Signer({
    ...settings().credentials,
    method,
    url: url.toString(),
    headers,
    service: "s3",
    region: "auto",
    signQuery: true,
    // aws4fetch leaves content-type and content-length out of a signature by
    // default, so that fetch can set them. Binding them is the whole point here.
    allHeaders: true,
    datetime: signedAt ? amzDate(signedAt) : undefined,
  });
  return (await signer.sign()).url.toString();
}

/**
 * A URL the browser can PUT one specific file to, for ten minutes.
 *
 * Comes with the headers the browser has to send, because they are part of the
 * signature: a different Content-Type, size or Cache-Control and R2 refuses.
 */
async function presignPut(key, { contentType, contentLength, cacheControl }) {
  const headers = { "content-type": contentType, "content-length": String(contentLength) };
  if (cacheControl) headers["cache-control"] = cacheControl;
  const url = await presign("PUT", key, { headers, expiresIn: PUT_URL_SECONDS });
  return {
    url,
    method: "PUT",
    // Content-Length is signed but not listed: the browser computes it from the
    // body and refuses to let script set it.
    headers: {
      "Content-Type": contentType,
      ...(cacheControl ? { "Cache-Control": cacheControl } : {}),
    },
    expires_at: Math.floor(Date.now() / 1000) + PUT_URL_SECONDS,
  };
}

/** A read URL, and how long the redirect to it may be cached. */
async function presignGet(key) {
  const now = Math.floor(Date.now() / 1000);
  const hourStart = now - (now % READ_WINDOW_SECONDS);
  const url = await presign("GET", key, {
    expiresIn: 2 * READ_WINDOW_SECONDS,
    signedAt: hourStart,
  });
  return { url, maxAge: Math.max(60, hourStart + READ_WINDOW_SECONDS - now) };
}

async function head(key) {
  const res = await settings().client.fetch(objectUrl(key), { method: "HEAD" });
  if (res.status === 404) return null;
  if (!res.ok) throw new Error(`R2 HEAD ${key} failed with ${res.status}`);
  return {
    bytes: Number(res.headers.get("content-length")),
    contentType: res.headers.get("content-type") || "",
    etag: res.headers.get("etag"),
    cacheControl: res.headers.get("cache-control"),
  };
}

async function getText(key, maxBytes) {
  const res = await settings().client.fetch(objectUrl(key));
  if (!res.ok) throw new Error(`R2 GET ${key} failed with ${res.status}`);
  const length = Number(res.headers.get("content-length"));
  if (maxBytes && length > maxBytes) {
    throw new Error(`${key} is ${length} bytes, over the ${maxBytes} byte limit`);
  }
  return res.text();
}

async function remove(key) {
  const res = await settings().client.fetch(objectUrl(key), { method: "DELETE" });
  if (!res.ok && res.status !== 404) throw new Error(`R2 DELETE ${key} failed with ${res.status}`);
}

function xml(value) {
  return String(value).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}

/**
 * Replace the bucket's CORS policy. Used by `npm run r2:cors`, never by the app.
 *
 * Changing bucket settings needs an Admin Read & Write token; the app's own
 * token only needs Object Read & Write, so this can fail with a 403 on a
 * correctly configured deployment.
 */
async function putBucketCors(rules) {
  const tags = (name, values = []) => values.map((v) => `<${name}>${xml(v)}</${name}>`).join("");
  const body =
    '<CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/">' +
    rules
      .map(
        (rule) =>
          "<CORSRule>" +
          tags("AllowedOrigin", rule.allowedOrigins) +
          tags("AllowedMethod", rule.allowedMethods) +
          tags("AllowedHeader", rule.allowedHeaders) +
          tags("ExposeHeader", rule.exposeHeaders) +
          (rule.maxAgeSeconds ? `<MaxAgeSeconds>${rule.maxAgeSeconds}</MaxAgeSeconds>` : "") +
          "</CORSRule>",
      )
      .join("") +
    "</CORSConfiguration>";

  const res = await settings().client.fetch(bucketUrl("cors"), {
    method: "PUT",
    body,
    headers: {
      "Content-Type": "application/xml",
      "Content-MD5": crypto.createHash("md5").update(body).digest("base64"),
    },
  });
  if (!res.ok) {
    const err = new Error(`R2 refused the CORS policy (${res.status}): ${(await res.text()).slice(0, 300)}`);
    err.status = res.status;
    throw err;
  }
}

module.exports = {
  PUT_URL_SECONDS,
  problem,
  isConfigured,
  mode,
  isSafeKey,
  publicUrl,
  presignPut,
  presignGet,
  head,
  getText,
  remove,
  putBucketCors,
};
